In [8]:
from IPython.display import display
import numpy as np
#1.
arr1=np.arange(1,16+1)
display(arr1)
arr1.reshape(4,4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
#2.
arr2=np.arange(10,50,5)
display(arr2)
arr2.reshape(2,4)

array([10, 15, 20, 25, 30, 35, 40, 45])

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [36]:
#3. randint
arr3=np.random.randint(1,100,(3,3))
display(arr3)
print("min:",arr3.min())
print("max:",arr3.max())

array([[94, 90, 89],
       [69, 17, 62],
       [28, 50, 25]])

min: 17
max: 94


In [58]:
#4.
arr4=np.random.randint(0,20,10)
display(arr4)
print("first 5:",arr4[0:5])
print("even index:",arr4[0:len(arr4):2])
print("reverse:",arr4[::-1])

array([10,  4,  5, 19, 19,  4, 12,  2, 16, 19])

first 5: [10  4  5 19 19]
even index: [10  5 19 12 16]
reverse: [19 16  2 12  4 19 19  5  4 10]


In [74]:
#5.
arr5=np.random.randint(1,50,(4,5))
display(arr5)
print("2nd row:",arr5[1])
print("4th column:",arr5[ :,3])

array([[41, 18, 38, 42, 44],
       [24, 31, 27, 10, 19],
       [18, 19, 27, 27,  1],
       [38,  7, 46, 27, 45]])

2nd row: [24 31 27 10 19]
4th column: [42 10 27 27]


In [86]:
arr6=np.random.randint(0,100,15)
display(np.arange(0,15))
display(arr6)
print("index of max value:",arr6.argmax())
print("index of min value:",arr6.argmin())
np.save("15-nums.npy",arr6)
arr_5=arr6[arr6%5==0]
display(arr_5)
display(arr6[(arr6<10)|(arr6>50)])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([65, 15, 18, 23, 49, 93, 14, 50, 44, 20, 56,  0, 75, 89, 76])

index of max value: 5
index of min value: 11


array([65, 15, 50, 20,  0, 75])

array([65, 93, 56,  0, 75, 89, 76])

In [164]:
max_len=None
max_seed=10
max_arr=np.zeros(15,dtype=int)
for seed in range(10, 101):
    np.r
    arr7=np.random.randint(0,100,15)
    l=len(arr7[arr7>80])
    if max_len is None or l>max_len:
        max_len=l
        max_seed=seed
        max_arr=arr7
print(f"max seed:",max_seed)
print(f"max length:",max_len)
print(f"max array:",max_arr)

max seed: 49
max length: 8
max array: [48 87 36  0 58 88 99 99 89  6 90 75 37 97 97]
